### ISSUE TITLE
Using album with large amount of detectors

### ISSUE THREAD

**Issue by klauer** [NSLS-II/album#8]
This nearly gives firefox a heart-attack:

<img width="1385" alt="albums-bokehd" src="https://cloud.githubusercontent.com/assets/5139267/10229441/44732362-6846-11e5-92c0-d1c002126522.png">

The run pictured is from my development environment, so you won't see that uid in the HXN metadatastore. I think for testing purposes, we should be looking at data sets with 100+ detectors.

**Comment by ericdill** [comment]
Thanks for the update.  It does indeed sound like a good idea to run some of our stuff through its paces with larger data sets

**Comment by mrakitin** [comment]
I've never heard of this project. What's the purpose?
